version: "3.8"

services:
  mysql: # Mysql container
    image: mysql:5.7.31
    ports:
      - 3306:3306
    volumes:
      - ../../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      localnetwork:
        ipv4_address: 162.11.1.103

  php: # Php container (With nginx and supervisor)
    deploy:
      resources: # Resources allocations for php container
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    build:
      context: ../.
      dockerfile: Dockerfile
      target: php_fpm
    volumes:
      - ../../:/var/www
    links:
      - mysql
      - rabbitmq
      - redis
    tty: true
    ports:
      - "8080:80"
    networks:
      localnetwork:
        ipv4_address: 162.11.1.103

  varnish: # Reverse proxy clients-server
    build:
      context: ../.
      dockerfile: Dockerfile
      target: varnish
    networks:
      localnetwork:
        ipv4_address: 162.11.1.103
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
    restart: unless-stopped

  redis: # Redis (For cache)
    image: redis:5.0
    networks:
      localnetwork:
        ipv4_address: 162.11.1.103

  rabbitmq:
    image: "rabbitmq:3.7-management"
    environment:
      RABBITMQ_DEFAULT_USER: $RABBIT_MQ_USER_NAME
      RABBITMQ_DEFAULT_PASS: $RABBIT_MQ_USER_PASSWORD
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      localnetwork:
        ipv4_address: 162.11.1.103

networks:
  localnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.11.1.0/24
          gateway: 162.11.1.1
